from typing import Protocol

from app.services.mock.client import MockWBClient
from app.services.mock.token import is_mock_token
from app.services.wb_client import WBClient


class WBClientProtocol(Protocol):
    async def ping(self) -> bool: ...
    async def get_seller_info(self) -> dict: ...
    async def get_sales(self, date_from): ...
    async def get_orders(self, date_from): ...
    async def get_stocks(self, date_from): ...
    async def get_sales_funnel(self, date_from, date_to): ...
    async def get_region_sales(self) -> list: ...


def create_wb_client(api_token: str) -> WBClient | MockWBClient:
    if is_mock_token(api_token):
        return MockWBClient(api_token)
    return WBClient(api_token)
